### ISSUE TITLE
Generate wrong calcChain.xml

### ISSUE THREAD

**Issue by liuwayne10** [cuba-platform/yarg#10]
I have a large xlsx file that contains one summary sheet that refers to 30 other sheets.
I can generate the report without error with Yarg.  However, when I open the output xlsx file, it errors out saying there problem in the content and asking me if I want to correct it or not.  If I click yes, it prompts message:  **Removed Records: Formula from /xl/calcChain.xml part (Calculation properties)**.
I can remove /xl/calcChain.xml with manually, so it force Excel to regenerate automatically when open it.  However, I wonder why it doesn't generate correctly in the beginning.

**Comment by tinhol** [comment]
Hello.

Could you please attach your template (or sample), and I will try to reproduce and fix it.
Also, which version do you use?
Thank you,

**Comment by liuwayne10** [comment]
Hi:  The file is business confidential.  I am not able to expose it.  I will see if I can build my own sample file to reproduce it.

By the way, I notice some of the formula depends on other formulas doesn't get evaluate when I open it.  I have to save the file to make it evaluate.  Is it expected behavior?  Is there are configuration I can set to make it automatically evaluate?

Thanks.

**Comment by tinhol** [comment]
If you use Microsoft Excel - formulas should be evaluated automatically. In Open/Libre Office it might be necessary to evaluate formulas with special manual action. Unfortunately I can not find it in my Libre Office for now.

**Comment by tinhol** [comment]
In modern Libre/Open Office builds formulas usually are recalculated automatically.
Though you still can recalculate them with SHIFT+CTRL+F9 shortcut.
