### ISSUE TITLE
Content inliners are not applied for some DOCX templates

### ISSUE THREAD

**Issue by soraksh** [cuba-platform/yarg#110]
### Environment

- YARG version: 2.1.5

### Description of the bug

- See 2 DOCX report templates with image parameters `widePictureId` and `portraitPictureId`:
[Trade report template.docx](https://github.com/cuba-platform/yarg/files/3181317/Trade.report.template.docx)
[Trade report template - new.docx](https://github.com/cuba-platform/yarg/files/3181319/Trade.report.template.-.new.docx)
- Both pictures should be formatted as `${bitmap:275x200}`
- First template works fine and inliners are applied to `widePictureId` and `portraitPictureId` parameters. For second template inliners are not applied: 
![f003c837de2a06f6741e0c66dc7954326c925c84](https://user-images.githubusercontent.com/23614267/57756132-aba78300-7703-11e9-8251-acb65f9bae57.png)

[Cuba forum topic](https://www.cuba-platform.ru/discuss/t/ne-otobrazhayutsya-kartinki-v-otchete-posle-izmenenij-v-shablone/3058)

**Comment by soraksh** [comment]
Problem sometimes occurs if 2 or more params placed in same cell/line.

**Comment by andreysubbotin** [comment]
Include in Reports 7.1
