### ISSUE TITLE
Question on DOCX Formatter

### ISSUE THREAD

**Issue by adhawan325** [cuba-platform/yarg#122]
We have the docx template setup as follows:

Name
Address Line 1
Address Line 2
City State Zip

Half the time, Address Line 2 is blank (data does not exist).  In this case, is it possible to "hide" the Address Line 2 and Show only:
Address Line 1
City State Zip

Thank you for your help!

**Comment by knstvk** [comment]
Please use https://www.cuba-platform.com/discuss/c/support for questions.
