### ISSUE TITLE
Possible File leaks in XLSFormatter and DocFormatter

### ISSUE THREAD

**Issue by foxalfabravo** [cuba-platform/yarg#13]
Reading the code, I noticed that DocxFomatter and  XlsxFormatter both end by closing the outputStream

    IOUtils.closeQuietly(outputStream);

But DocFormatter & XlsFormatter don't

**Comment by tinhol** [comment]
Thank you for the feedback. We will fix it in next release.

**Comment by tinhol** [comment]
Fixed in the master branch.
