### ISSUE TITLE
Loosing digital signature of macro excel template on output 

### ISSUE THREAD

**Issue by VarmaTech** [cuba-platform/yarg#131]
when i use Excel template with macro code, everything work fine but i am lost digital signature on output excel file . please let me know how to fix it .

**Comment by dtaimanov** [comment]
> when i use Excel template with macro code, everything work fine but i am lost digital signature on output excel file . please let me know how to fix it .

YARG doesn't support [digital signature](https://en.wikipedia.org/wiki/Digital_signature) generation, so it is necessary to sign an output file manually.
