### ISSUE TITLE
Fix links in README.md

### ISSUE THREAD

**Issue by owlet1997** [cuba-platform/yarg#153]
### Environment

- YARG version: 2.2-SNAPSHOT

### Description of the bug or enhancement

wrong links in README.md

**AR:**
links to `bintray` repository
![image](https://user-images.githubusercontent.com/45730069/126317331-c57b669a-8703-4b9a-9d9c-2699b7ee2fb1.png)

**ER:**
links to actual repository

**Comment by gorbunkov** [comment]
There should be a link to repo.cuba-platform.com
