### ISSUE TITLE
 Incorrect display of logical fields in the report

### ISSUE THREAD

**Issue by NikitaShchienko** [cuba-platform/yarg#154]
### Environment

- Platform version: 7.2 

### Description of the bug or enhancement

Boolean fields are displayed incorrectly.

Forum: https://www.cuba-platform.ru/discuss/t/otchet-xlsx-vyvodit-pustye-polosy-na-platform-7-2/4022

#### Minimal reproducible example
 
1. Create a new entity with a logical field
2. Create an edit and view screen for this entity
3. Create a report for this entity

Entity:
```
@NamePattern("%s|name")
@Table(name = "TESTREPORTBLANKLINES_TEST_ENTITY")
@Entity(name = "testreportblanklines_TestEntity")
public class TestEntity extends StandardEntity {
    private static final long serialVersionUID = -8663906688552045810L;

    @Column(name = "NAME")
    protected String name;

    @Column(name = "FLAG", nullable = false)
    protected Boolean flag = false;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getFlag() {
        return flag;
    }

    public void setFlag(Boolean flag) {
        this.flag = flag;
    }
}
```

Data:
![image](https://user-images.githubusercontent.com/47520144/76617205-3e40ca80-653f-11ea-8c86-f63268fc1d23.png)

Report Template:
![image](https://user-images.githubusercontent.com/47520144/76617141-15b8d080-653f-11ea-9d40-33aa21330669.png)

Report:
![image](https://user-images.githubusercontent.com/47520144/76617109-fe79e300-653e-11ea-80d6-7a62867b86fc.png)

**Comment by Desire456** [comment]
Yarg issue https://github.com/cuba-platform/yarg/issues/154
