### ISSUE TITLE
Use logger facade instead of explicit log4j dependency

### ISSUE THREAD

**Issue by lospejos** [cuba-platform/yarg#17]
Please use a logging facade instead of setting the explicit log4j dependency, as per: http://stackoverflow.com/questions/9740569/logger-for-java-library/9741118#9741118 Otherwise you force your users to use a log4j which mostly is not the case (most of them do prefer a logback logging implementation). Thanks

**Comment by lospejos** [comment]
Also look here: https://www.slf4j.org/codes.html#multiple_bindings ("Note" part): 

> Embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api. When a library declares a compile-time dependency on a SLF4J binding, it imposes that binding on the end-user, thus negating SLF4J's purpose. When you come across an embedded component declaring a compile-time dependency on any SLF4J binding, please take the time to contact the authors of said component/library and kindly ask them to mend their ways.

**Comment by jreznot** [comment]
HI, thank you for the issue. Will fix it

**Comment by jreznot** [comment]
We are going to release version 2.0.0 that will use slf4j-api without backend. 
See changes here: https://youtrack.cuba-platform.com/issue/YARG-8

**Comment by jreznot** [comment]
We have released it! See readme, new binaries available in a public Bintray repository
