### ISSUE TITLE
Overlapping band regions

### ISSUE THREAD

**Issue by hakankb** [cuba-platform/yarg#21]
Hi team
How can i properly handle overlapping named regions in xlsx template ?
By overlapping regions, I mean regions that contain cells in common.

When regions of two band overlap, output document is not properly generated

Best regards

**Comment by tinhol** [comment]
Hello. Could you please provide an example? I'm not sure I understand why do you need overlapping bands, and I'm almost sure that the overlapping bands are not supported by the engine.

**Comment by tinhol** [comment]
Outdated ticket. Please create a new one (with an attached example) if you still have the issue.
