### ISSUE TITLE
Migrating from 1.0.59 to 2.x

### ISSUE THREAD

**Issue by jchappelle** [cuba-platform/yarg#28]
Hi,

Is there any documentation on the significant changes between 1.0.59 and 2.x? I'm considering upgrading our application to the new version but I'm trying to evaluate the risk/reward. 

Thanks!

**Comment by jreznot** [comment]
Hi,

There are few major changes primarily in dependencies and module structure, described here: https://github.com/cuba-platform/yarg/releases/tag/yarg-2.0.1

It will be really simple migration if you already use Java 8.
