### ISSUE TITLE
Not showing LOGO image when exporting from Docx template to HTML

### ISSUE THREAD

**Issue by srinivas460** [cuba-platform/yarg#31]
As per the earlier Post [https://github.com/cuba-platform/yarg/issues/22](url) given a fix but when
i tries with maven repository dependency, but i got one jar Yarg-api-2.0.1.jar where i don't find the Fixed. See [https://github.com/cuba-platform/yarg/commit/5de0ec686f8694759159a1aab0d2d0e71eb2e5d0](url)

 please help me to find solution

**Comment by tinhol** [comment]
Could you please try to user bintray, as described [here](https://github.com/cuba-platform/yarg#how-to-add-dependency)?

By the way, you should get at least 2 jars - yarg and yarg-api.

**Comment by srinivas460** [comment]
Tried above but i get error like 

```
Caused by: org.apache.xml.dtm.DTMException: No more DTM IDs are available

Caused by: javax.xml.transform.TransformerException: No more DTM IDs are available
```

**Comment by srinivas460** [comment]
Still not able to export Docx to html . also in resent version 2.0.11 , docx to html and docx to pdf are not working..

here is sample code of mine..
[Uploading temp1.docx…]()

`code:
public static void testDocx(ReportOutputType Type) throws Exception {
		File file = new File(tempath.getAbsolutePath());
		ReportBuilder reportBuilder = new ReportBuilder();
		ReportTemplateBuilder reportTemplateBuilder = new ReportTemplateBuilder().documentPath(file.getPath())
				.documentName(file.getName()).outputType(Type).readFileFromPath();
		reportBuilder.template(reportTemplateBuilder.build());

		BandBuilder bandBuilder = new BandBuilder();

		bandBuilder = new BandBuilder();
		ReportBand tabledata = bandBuilder.name("Table1").query("Data_set_1", "return " + getTableData(), "groovy")
		.orientation(BandOrientation.HORIZONTAL).build();

		reportBuilder.band(tabledata);

		Report report = reportBuilder.build();

		Reporting reporting = new Reporting();

		DefaultFormatterFactory defaultFormatterFactory = new DefaultFormatterFactory();
		OfficeIntegration office=new OfficeIntegration("C:/Program Files/LibreOffice 5/program/", 6555,6556,7556,7555);
		office.setDisplayDeviceAvailable(false);
		office.setTemporaryDirPath(folderpath);
		office.setTimeoutInSeconds(300);
		office.setCountOfRetry(5);
		
		defaultFormatterFactory
				.setOfficeIntegration(office);
		reporting.setFormatterFactory(defaultFormatterFactory);

		reporting.setLoaderFactory(
				new DefaultLoaderFactory()
				.setGroovyDataLoader(new GroovyDataLoader(new DefaultScriptingImpl()))
				.setJsonDataLoader(new JsonDataLoader()));

//		String HeadersList=getheaderData();
		ReportOutputDocument reportOutputDocument = reporting.runReport(new RunParams(report),
				new FileOutputStream(folderpath+"/result_"+FilenameUtils.removeExtension(file.getName())+"."+Type.getId()));
	}

	static int FinalColumns =3;
	static int DataRows = 5;
	private static String getTableData() {
		// TODO Auto-generated method stub
		ArrayList<String> arritm = new ArrayList<>();
		JSONArray arr = new JSONArray();
		JSONArray farr = new JSONArray();
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < DataRows; i++) {
			sb = new StringBuilder();
			for (int j = 0; j < FinalColumns; j++) {
				// {"unit":9,"price":2,"qty":1,"desc":"items : 1"}
				sb.append("'COL" + j + "':'COL" + j + "'");
				if (j != FinalColumns - 1) {
					sb.append(",");
				}

			}
			arritm.add("[" + sb + "]");
		}

		return arritm.toString();
	}
	

`

**Comment by tinhol** [comment]
Hello.

I've run exactly your code and it has produced an HTML for me. I've also checked the PDF creation, and it worked as well. 

Could you please provide your stacktrace? 
Also, have you checked if your Libre Office runs fine from the folder you've provided in the code?
