### ISSUE TITLE
After generating the excel file using excel template issue

### ISSUE THREAD

**Issue by srinivas460** [cuba-platform/yarg#32]
Hi , 
Getting a Issue like when i open excel file after generating from excel template .

After open the file it is promoting to  **we found a problem with some content in 'file', Do you want us to try to recover as much as we can ?**  here is the error log below ...

when click yes, below is showing in error log...
```
 <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
 <recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
 	<logFileName>error167560_01.xml</logFileName>
 	<summary>Errors were detected in file 'filepath.xlsx'</summary>
 	<removedRecords>
		<removedRecord>Removed Records: Cell information from /xl/worksheets/sheet1.xml part</removedRecord>
 	</removedRecords>
 </recoveryLog>
```

**Comment by tinhol** [comment]
Could you please provide your tempalte and the resulting file?

**Comment by srinivas460** [comment]
Thanks for your response. found the solutions for it . issue is fixed now .
