### ISSUE TITLE
Not able set Table as band 

### ISSUE THREAD

**Issue by srinivas460** [cuba-platform/yarg#33]
Hi,
I am trying to build Excel report using excel template with Table inside , but getting error 

```
java.lang.NullPointerException
	at com.haulmont.yarg.formatters.impl.xlsx.Document.clearWorkbook(Document.java:246)
	at com.haulmont.yarg.formatters.impl.XlsxFormatter.renderDocument(XlsxFormatter.java:87)
	at com.haulmont.yarg.reporting.Reporting.generateReport(Reporting.java:133)
```
can any one help me out ..

My Sample Code below : 
**Template file**
[incomes.xlsx](https://github.com/cuba-platform/yarg/files/1566642/incomes.xlsx)

**Code:**
```
 public void testIncomesReport() throws Exception {
        Report report = new DefaultXmlReader()
                .parseXml(readFileToString(new File("./incomes.xml")));

        Reporting reporting = new Reporting();
        reporting.setFormatterFactory(new DefaultFormatterFactory());
        reporting.setLoaderFactory(
                new DefaultLoaderFactory()
                        .setGroovyDataLoader(new GroovyDataLoader(new DefaultScriptingImpl())));

        ReportOutputDocument reportOutputDocument = reporting.runReport(
                new RunParams(report), new FileOutputStream("./result_incomes.xlsx"));
    }
```
**Xml Data :**
```
<?xml version="1.0" encoding="UTF-8"?>

<report name="report">
    <templates>
        <template code="DEFAULT" documentName="incomes.xlsx" documentPath="./incomes.xlsx" outputType="xlsx" outputNamePattern="incomes.xlsx"/>
    </templates>
    <rootBand name="Root" orientation="H">
        <bands>
		 <band name="TableData" orientation="H">
                <queries>
                    <query name="Data_set_1" type="groovy">
                        <script>
                            return [['COL0':'Jan', 'COL1':10000], ['COL0': 'Feb', 'COL1': 12000], ['COL0': 'March', 'COL1': 15000], ['COL0': 'Apr', 'COL1': 12000]]
                        </script>
                    </query>
                </queries>
            </band>
        </bands>
        <queries/>
    </rootBand>
</report>

```

**Comment by tinhol** [comment]
Hello.

I've checked your code and your template, and found out that the named range in XLXS file ("TableData") is not properly set. I'm not sure why it's so, but I've just copied the content to a new file and created a new named range and it worked fine.

BTW, do you use Libre Office for XLXS files creation? In some cases it might lead to issues...

**Comment by srinivas460** [comment]
Hi tinhol,

can you give me your working copy (code and Template), ill check what was the mistake done by me .

i am using LibreOffice only,

**Comment by tinhol** [comment]
Hello.

Please see the attached patch and additionally the template.

[IssuesPatch.txt](https://github.com/cuba-platform/yarg/files/1621524/IssuesPatch.txt)
[incomes.xlsx](https://github.com/cuba-platform/yarg/files/1621532/incomes.xlsx)

**Comment by srinivas460** [comment]
Hi ,
thanks for the response..

the give template by you , is a working process.. 

But my problem is when i insert table to columns it automcatically make it as Table1 in NamgeRange formulae .. so later when i run with Yarg , it will give a empty output.. 


below NameRange Formula , Output will be Empty
![table_band1](https://user-images.githubusercontent.com/7511959/34860438-69e6887c-f783-11e7-8c51-2d5c05e4ac20.JPG)


below NameRange Formula , Output will be success..
![table_band2](https://user-images.githubusercontent.com/7511959/34860448-795f8286-f783-11e7-9bb4-ec6093271007.JPG)


i think when i insert table to template yarg is not reading the namesrange and giving empty output..

**Comment by tinhol** [comment]
Hello.

Do you mean that you insert the table from another document?
Even if OpenOffice changes the name of the named range, could you change it back to TableData?
