### ISSUE TITLE
How to create Pivot table in excel

### ISSUE THREAD

**Issue by srinivas460** [cuba-platform/yarg#34]
Hi,
I want to show a pivot table in excel using excel template where data will be inserted dynamically
can any one help me out..

**Comment by tinhol** [comment]
Hello.

For now Pivot Table is not supported in YARG directly.
The only thing you can do is to create pivot table which will look at very long range, which will be filled by the report data.

Though, we are planning to implement the PivotTable support in the next releases.

**Comment by tinhol** [comment]
Hello.

I have implemented the very first version of Pivot Tables support.

Could you please look at it, and check if it satisfies your requirements?

Thank you.

**Comment by srinivas460** [comment]
HI tinhol, 
Thanks a lot for the update..

what version of Yarg shall i have to use ?

**Comment by tinhol** [comment]
We have not released the new version yet, but you can build YARG from master branch.

The example is smoketest/pivot.xlsx and smoketest.XlsxSpecificTest#testPivot.

**Comment by tinhol** [comment]
Hello.
The latest version 2.0.12 has been published in Maven Central.
Please check it.
Thank you.
