### ISSUE TITLE
Handle null parameters in reports

### ISSUE THREAD

**Issue by wrover** [cuba-platform/yarg#35]
Since I have not received any ideas at Cuba Platform Forum, going to post a question here.

>Hi there,
>looking for a way to specify sort of like default values in reports.
>I.e. having null value in DataBand I need to put down N/A for example in report.
>Any ideas? Custom formats will work, but that’s another story - the absense to plug in your custom formatter is terrible to be honest.
>Moreover, it looks that we have a requirement to provide ability to change to default values in templates.
>BTW, we are implemented external API dataloader for YARG, is anyone interested in PR?

BR,
Ilia Rodionov.

**Comment by tinhol** [comment]
Hello.

Have you tried to override the com.haulmont.yarg.reporting.DataExtractor implementation?

**Comment by wrover** [comment]
Hi, 
yes, we modified it's logic. 
Actually the point is to let templates authors ability to decide what should be used when a null (or empty) value is encountered. In some reports users need to have '---' in others 'N/A'. No reason to have this values stored in application - it's solely a matter of representation, isn't it?

**Comment by tinhol** [comment]
Hello.
Well, you are right. In your case even custom value formatter would not help, because our file formatters just ignore null values.

Let me think about it, and I will provide some implementation in next releases.

**Comment by wrover** [comment]
Thanks in advance, it would be great. Don't hesitate to contact if I can give you a hand somehow.

**Comment by tinhol** [comment]
Hello,

I have implemented the feature in master branch.

Could you please take a look?

**Comment by wrover** [comment]
Hi, 
looks as if that should work. I am going to try it later on.

**Comment by wrover** [comment]
Hi,
this fully covers what we were talking about. Thank you.
What version of the CUBA platform will bring yarg 2.0.12 with the reporting?

**Comment by andreysubbotin** [comment]
Hi
YARG 2.0.12 is used only for 6.9 CUBA. The only beta version of CUBA 6.9 is available.
But you can specify dependency to YARG 2.0.12 in the build.gradle:

1. Add dependency for core module: 
```
compile('com.haulmont.yarg:yarg:2.0.12')
```
1.  Add dependency for global module:
```
compile('com.haulmont.yarg:yarg-api:2.0.12')
```

**Comment by wrover** [comment]
Andrey, thanks a lot, it works well. The only thing I'd like to tell -- eventually I put our formatters classes in a standalone library because when being loaded within the app classloaders they are unavailable for yarg library (not sure that's what's going on actually, but the error is noClassDefFound). But this is just fine anyway.

**Comment by andreysubbotin** [comment]
Thanks @wrover 
I've created an issue: https://github.com/cuba-platform/yarg/issues/44
