### ISSUE TITLE
Found a Issue when Converting Word to Pdf ..

### ISSUE THREAD

**Issue by srinivas460** [cuba-platform/yarg#37]
Hi Yarg..

I am using Yarg 2.0.11 version .

i am trying to generate a PDF document using Word Template by OpenOffice , as it works fine in Windows OS.
Found Issue in Linux Version OS  as i am Using Oracle Linux Server 6.9 
Result in Linux:
[word-pdf-linux.pdf](https://github.com/cuba-platform/yarg/files/1651501/word-pdf-linux.pdf)

Result in Windows:
[word-pdf-windows.pdf](https://github.com/cuba-platform/yarg/files/1651502/word-pdf-windows.pdf)

so can u help me out with it

**Comment by tinhol** [comment]
Hello.

Which version of Open/Libre Office do you use on Win and on Linux?

**Comment by srinivas460** [comment]
In Linux Open Office : 4.1.2
In Windows Open Office : 4.1.2

**Comment by tinhol** [comment]
Hello.
Sorry, but I could not reproduce it. 

Have you properly setup Open Office connection path and other properties? 

Could you please try to debug it (com.haulmont.yarg.formatters.impl.DocxFormatter#saveAndClose) and check which logic handle you PDF conversion?
