### ISSUE TITLE
CR: Make yarg 2.x available at maven central

### ISSUE THREAD

**Issue by f-aubert** [cuba-platform/yarg#43]
Hello, I apologize if I shouldn't open such an issue, but I would welcome yarg 2.x to be available at Maven Central. It's really complex for us to enable custom 3rd party repositories due to organization and security rules.. Thanks for your consideration.

**Comment by jreznot** [comment]
Hi,
It is already available in jcenter repository. t

**Comment by f-aubert** [comment]
Unfortunately it's a policy of our organisation, which is beyond my power. Would it be possibly for you? I noticed you have an older version there, 1.0.70, https://search.maven.org/#artifactdetails%7Ccom.haulmont.yarg%7Cyarg%7C1.0.70%7Cjar

**Comment by tinhol** [comment]
Hello.
The latest version 2.0.12 has been published in Maven Central. 
Please check it.
Thank you.
