### ISSUE TITLE
Support for remote OOServer

### ISSUE THREAD

**Issue by wrover** [cuba-platform/yarg#70]
Hi, I'd like to have one issue clarified. I wonder what’s the reason the team decided to use local OOServer always using 127.0.0.1 in the code? Does this have any severe grounds? Would it be better to provide ability to run Office (or may be even several ones) and connect to them in the remote manner on demand?
Regards,
Ilia.

**Comment by andreysubbotin** [comment]
Remote OO Server requires writing server side application that manages LibreOffice processes (starts and stops). What are the benefits of the remote invocation?
I don't see any cases of such usage. You can run different YARG servers on different machines and print reports using YARG REST (https://github.com/cuba-platform/yarg/blob/master/core/modules/server/src/com/haulmont/yarg/server/)

**Comment by wrover** [comment]
For yarg itself it can't seem to be profitable, you are right. The original intention emerged when use CUBA Reporting. We used to deploy a CUBA app in container environment. The need to include LibreOffice to the image drastically raises its size. The option to use separate office containers could help I suppose.
