### ISSUE TITLE
Report generation hangs if the defined ooo port is occupied by another program

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/yarg#76]
See also  #75 

### Environment

- YARG version: 2.0.14 (the latest 
platform 6.10)

### Description of the bug or enhancement

1) Adjust OOO integration in Reports. Define an already used port in cuba.reporting.openoffice.ports. (8111 is used by Studio)
```code
reporting.openoffice.path = C:/Program Files (x86)/LibreOffice 5/program
reporting.openoffice.docx.useOfficeForDocumentConversion = true
cuba.reporting.openoffice.ports = 8110,8111
```
2) Start the application
3) Create a report with DOCX template and PDF output 
4) Launch the report (8110 is used at firt run)
5) Launch the report again (8111)

**Expected behavior**
The port is in use so the next one will be taken or the report generation will be interrupted by timeout.

**Actual behavior**
Report generation hangs on connecton.open()

**Comment by andreysubbotin** [comment]
You must specify only unused ports for LibreOffice.
