### ISSUE TITLE
Unable to execute groovy script with for loop

### ISSUE THREAD

**Issue by kkorada** [cuba-platform/yarg#77]
### Environment

- YARG version: 2.0.4
- Database: H2
- Operating system: Windows

### Description of the bug or enhancement
unable to execute groovy script with for loop

- Minimal reproducible example
```
def monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
def quatersMap = ["quaterName1": "Q1'", "quaterName2": "Q2'", "quaterName3": "Q3'", "quaterName4": "Q4'", "quaterName5": "Q1'", "quaterName6": "Q2'", "quaterName7": "Q3'", "quaterName8": "Q4'"];
int currentYear = Calendar.getInstance().get(Calendar.YEAR) % 100;
int prevYear = currentYear - 1;
int currMonth = Calendar.getInstance().get(Calendar.MONTH);
int currQuater = currMonth / 3 + 1;
for (i = 1; i <= 8; i++) {
    if (i <= 4) {
        quatersMap['quaterName' + i] += prevYear;
    } else {
        if (i - 4 < currQuater) {
            quatersMap['quaterName' + i] += currentYear;
        } else if (i - 4 == currQuater) {
            quatersMap['quaterName' + i] = 'QTD ' + monthNames[currMonth];
        } else {
            quatersMap['quaterName' + i] = 'NA';
        }
    }
}
return [quatersMap];
```
- Expected behavior
should return values
- Actual behavior
throwing error while parsing xml document

**Comment by jreznot** [comment]
Hi,

Could you provide a test project or unit test for YARG ?

**Comment by kkorada** [comment]
I got the issue, `<` symbol is giving me a problem. I need to escape it with &lt;

**Comment by kkorada** [comment]
i have one question, could you please let me know how to set parameters to script in sql data loader

**Comment by jreznot** [comment]
Usually, we discuss questions on the forum: https://www.cuba-platform.com/discuss/ Could you please open topic there?
