### ISSUE TITLE
Unable to use transactional or entity manager in groovy data loader

### ISSUE THREAD

**Issue by kkorada** [cuba-platform/yarg#79]
### Environment

- YARG version: 2.0.12 

### Description of the bug or enhancement
Unable to use entity manager or transactional closure in groovy script data loader.

- Minimal reproducible example
```
def result = []
transactional { em ->
    def query = em.createQuery('select u from sec$User u where u.group.id = ?1 and u.active = ?2')
    query.setParameter(1, parentBand.getParameterValue('groupId'))
    query.setParameter(2, params['active'])
    query.resultList.each { user ->
        result.add(['userLogin': user.login, 'userName': user.name])
    }
}
return result
```

- Expected behavior
to return users data

- Actual behavior
it is throwing exception

**Comment by andreysubbotin** [comment]
Do you use YARG or CUBA Reporting addon? YARG doesn't support transactional statement, only CUBA Reporting addon supports it.

**Comment by kkorada** [comment]
i have used YARG reporting. how to use CUBA reporting is it open source can it be used in any java application same as YARG ?

**Comment by jreznot** [comment]
Unfortunately, you can use CUBA reporting only in CUBA based applications, it is paid add-on for CUBA Platform.
