### ISSUE TITLE
Define named ranges in Report output file

### ISSUE THREAD

**Issue by mariodavid** [cuba-platform/yarg#9]
Hi,

i've a question about the usage of named ranges in XLSX templates.

As described in the [Formatters section](https://github.com/cuba-platform/yarg/wiki/Formatters) the bands should have equivalents in the Name regions section of the excel template. In the [template file](https://github.com/cuba-platform/yarg/blob/master/core/modules/core/test/sample/incomes/incomes.xlsx) for the incomes example you created these name ranges:
- Incomes
- Header
- Footer
- Chart

What i don't really get is the following situation:

When something like a chart or a formula within the template references these data regions, why they are not referencing them by their name. An example of this can be found in your article about [chart creation](https://github.com/cuba-platform/yarg/wiki/Xlsx-Charts-creation). In [this](https://github.com/Haulmont/yarg/wiki/pictures/chart-creation/chart-creation4.png) image about the data reference the reference goes to $B$2 in the sheet. After executing the report, the data goes from $B$2 to $B$5 - nevertheless, the diagram is able to find out that this is the data region, not only $B$2 anymore. I find this really interesting that it seems to work, although i can't imagine how - perhaps i'm just missing the point.

I would have expected it to work when the following change would have been made:
1. The diagram references not $B$2 but "Incomes" via the name
2. In the resulting output file the name range "Incomes" exists and the value is $B$2:$B$5.

I got a little stuck while trying to do that with a pivot table and reference the defined name range for the data of the pivot table.

PS: i'm using YARG via the CUBA platforms integration.

Perhaps you can either give me a little hint why the name ranges are not part of the output file and it works anyway, or alternatively if there is a change to get the updated name ranges in the output file so that other elements of the template can reference it via the name.

Bye,
Mario

**Comment by tinhol** [comment]
Hello.

YARG does not keep named ranges in the result file (actually for no reason, probably it should). Instead, it does calculate formulas (and chart regions) offset and growth during file rendering, so if in the tempalte your formula was A5:A5 - in the result file it would be A5:A10, because the band has grown.

**Comment by mariodavid** [comment]
Hi,

does this mean that the lib has to understand all mechanisms of excel (like pivot tables) and update the references from the different elements according to the data that has been put into the file? Or will it replace the references to the cells with the new references in a generic way?

From my personal opinion i think keeping the named ranges in the resulting file would be a good idea because it is more visible how to design the template (if the person is familiar with named ranges at least).

But if YARG does the magic in this case, i'll be fine with the current solution as well...

Thanks for the explanation!

Bye,
Mario
